const paragaraps = [
  "She nervously peered over the edge. She understood in her mind that the view wassupposed to be beautiful, but all she felt was fear. There had always been somethingabout heights that disturbed her, and now she could feel the full force of this unease. Shereluctantly crept a little closer with the encouragement of her friends as the fearcontinued to build. She couldn't help but feel that something horrible was about tohappen",
  "Dave watched as the forest burned up on the hill, only a few miles from her house. Thecar had been hastily packed and Marta was inside trying to round up the last of the pets.Dave went through his mental list of the most important papers and documents thatthey couldn't leave behind. He scolded himself for not having prepared these better inadvance and hoped that he had remembered everything that was needed. He continuedto wait for Marta to appear with the pets, but she still was nowhere to be seen.",
  "Turning away from the ledge, he started slowly down the mountain, deciding that hewould, that very night, satisfy his curiosity about the man-house. In the meantime, hewould go down into the canyon and get a cool drink, after which he would visit someberry patches just over the ridge, and explore among the foothills a bit before his nap-time, which always came just after the sun had walked past the middle of the sky. At thatperiod of the day the sun’s warm rays seemed to cast a sleepy spell over the silent",
  "While setting out on a new project or a business venture, commitment is required to see the project or business venture through. Just as a personal relationship flourishes with commitment, a goal requires to be pursued with complete commitment, to realize it. Lack of commitment has led to many good ideas being frittered away only because people did not pursue them with conviction.",
  "A goal which cannot sustain your interest for a long time presents a problem because it is very difficult to retain the commitment for it. It is, therefore, important that you set your goals carefully and systematically so that you don't have to regret later. If the work is such that it itself sustains your interests, then you will enjoy doing it in-spite of the difficulties and never feel bored of it.",
  "The government of India has been taking a flurry of measures to correct the gender bias and support women. For instance Priyadarshini - a pilot programme for women empowerment, Support to Training and Employment Programme - to develop skills of women for self and employment, Udaan- to promote girl education and Sukanya Samridhi Yojana under which girl child below 10 years will have bank accounts with more interest to name a few. These schemes are also an acknowledgment of the fact that gender bias is a reality, that women remain a neglected lot, and until that is tackled, women empowerment will remain a hollow idea.",
  "The 21 century is a century of movement and fluidity. Globalisation, aided by technological innovation, has redefined the idea of borders and identities. As more people move transcend borders and interact with people from different nationalities, they gain a new perspective on the world. Globalisation includes an inter-linking of trades, culture, political and social views and benefits countries as they adopt the best practices from all over the world to improve their own country. Access to international markets, rise in tourism, forex reserves, financial support, security are just some of the advantages of embracing globalisation.",
  "Education and empowerment go hand in hand. If we are to empower girls, it is imperative to give women access to education. It is no coincidence that an improvement in the condition of women has coincided with an increase in the literacy rates of women to more than 50 per cent today. It is also important, at the same time, to sensitise the men of the society on gender issues so that the existing gender bias can be wiped off.",
  "Cleanliness is necessary for good health. It is the most important hygiene habit. Dirt spreads diseases, because germs thrive in it. They move about with the dust in the air, so a dirty man is easily attacked with diseases. The man, who has a clean body and puts on clean clothes, is free from dirt and dust, and no disease can attack him easily. Daily bathing is a good habit. It keeps our body clean. We should keep our clothes, beddings, food, utensils, and all other things neat and clean. No dirt should be allowed to gather near our houses. We should also keep our teeth and nails clean. We should remember that cleanliness is next to godliness.",
  "The proverb says that health is wealth. It is truly said that of all things in the world health is the most valuable that one can possess. Money is no doubt a pleasant thing. However, it can give no pleasure to a man of ruined health. As body and mind are closely connected, the mind cannot be sound and cheerful without sound health.",
];